-- Add questions for Module 1 (Fotosintesis) with explanations
-- Mix of HOTS and regular questions for solo and multiplayer quiz

-- Regular Questions (13 total - sistem akan random pilih sesuai kebutuhan)
INSERT INTO questions (module_id, question, option_a, option_b, option_c, option_d, correct_answer, question_type, read_time, answer_time, explanation, created_at, updated_at) VALUES
(1, 'Seorang siswa menaruh tanaman di dalam ruangan gelap selama seminggu. Daunnya menjadi pucat dan tanaman tampak layu. Apa penyebab utama kondisi tersebut berdasarkan proses fotosintesis?', 'Tanaman kekurangan air', 'Tidak ada cahaya matahari sebagai sumber energi', 'Tanaman tidak menyerap karbon dioksida', 'Tanaman terlalu banyak oksigen', 'b', 'regular', 10, 15, 'Cahaya matahari adalah sumber energi utama untuk fotosintesis. Tanpa cahaya, klorofil tidak dapat menangkap energi untuk mengubah CO2 dan air menjadi glukosa, sehingga tanaman menjadi pucat dan layu.', NOW(), NOW()),

(1, 'Apa arti kata "synthesis" dalam istilah fotosintesis?', 'Cahaya', 'Menggabungkan atau menyusun', 'Energi', 'Warna hijau', 'b', 'regular', 10, 15, 'Kata "synthesis" berarti menggabungkan atau menyusun. Dalam fotosintesis, tumbuhan menggabungkan CO2 dan air dengan bantuan cahaya untuk menyusun/membuat glukosa sebagai makanan.', NOW(), NOW()),

(1, 'Mengapa tumbuhan disebut makhluk hidup autotrof?', 'Karena bisa bergerak mencari makanannya', 'Karena bisa membuat makanannya sendiri', 'Karena selalu membutuhkan hewan untuk hidup', 'Karena tidak membutuhkan air', 'b', 'regular', 10, 15, 'Autotrof berarti dapat membuat makanan sendiri. Tumbuhan disebut autotrof karena dapat melakukan fotosintesis untuk membuat glukosa sebagai makanannya sendiri tanpa harus mencari atau memakan makhluk lain.', NOW(), NOW()),

(1, 'Proses fotosintesis terutama terjadi di bagian tumbuhan yang mana?', 'Akar', 'Batang', 'Daun (kloroplas)', 'Bunga', 'c', 'regular', 10, 15, 'Fotosintesis terjadi di daun, tepatnya di dalam kloroplas yang mengandung klorofil. Daun memiliki struktur yang sesuai untuk menangkap cahaya dan melakukan pertukaran gas melalui stomata.', NOW(), NOW()),

(1, 'Gas apa yang diperlukan tumbuhan untuk fotosintesis?', 'Oksigen (O₂)', 'Karbon dioksida (CO₂)', 'Nitrogen (N₂)', 'Hidrogen (H₂)', 'b', 'regular', 10, 15, 'Karbon dioksida (CO₂) adalah bahan baku utama fotosintesis. CO₂ diserap dari udara melalui stomata dan dikombinasikan dengan air untuk membentuk glukosa dengan bantuan energi cahaya.', NOW(), NOW()),

(1, 'Lubang kecil pada daun tempat masuknya gas disebut…', 'Epidermis', 'Xilem', 'Stomata', 'Floem', 'c', 'regular', 10, 15, 'Stomata adalah pori-pori kecil pada permukaan daun yang berfungsi untuk pertukaran gas. Melalui stomata, CO₂ masuk dan O₂ keluar selama proses fotosintesis.', NOW(), NOW()),

(1, 'Zat apa yang membuat daun berwarna hijau dan berfungsi menangkap cahaya matahari?', 'Hemoglobin', 'Klorofil', 'Glukosa', 'Oksigen', 'b', 'regular', 10, 15, 'Klorofil adalah pigmen hijau dalam kloroplas yang bertugas menangkap energi cahaya matahari. Energi ini kemudian digunakan untuk mengubah CO₂ dan air menjadi glukosa dalam proses fotosintesis.', NOW(), NOW()),

(1, 'Air untuk fotosintesis diperoleh tumbuhan melalui…', 'Bunga', 'Daun', 'Akar', 'Stomata', 'c', 'regular', 10, 15, 'Akar menyerap air dari tanah bersama dengan mineral. Air ini kemudian dialirkan melalui batang ke daun untuk digunakan dalam proses fotosintesis sebagai bahan baku pembuatan glukosa.', NOW(), NOW()),

(1, 'Energi dari makanan hasil fotosintesis digunakan tumbuhan untuk…', 'Tumbuh tinggi', 'Membentuk bunga dan buah', 'Bertahan hidup', 'Semua benar', 'd', 'regular', 10, 15, 'Glukosa hasil fotosintesis digunakan tumbuhan untuk berbagai keperluan: sebagai sumber energi untuk tumbuh tinggi, membentuk organ seperti bunga dan buah, serta untuk mempertahankan proses kehidupan dasar.', NOW(), NOW()),

(1, 'Apa yang terjadi jika tumbuhan tidak bisa membuat makanan?', 'Tumbuh lebih cepat', 'Layu, berhenti tumbuh, atau mati', 'Menghasilkan lebih banyak oksigen', 'Daun menjadi lebih hijau', 'b', 'regular', 10, 15, 'Tanpa fotosintesis, tumbuhan kehilangan sumber energi utama. Akibatnya tumbuhan akan layu karena kekurangan nutrisi, berhenti tumbuh karena tidak ada energi, dan akhirnya mati.', NOW(), NOW()),

(1, 'Tanpa cahaya matahari, apa yang akan terjadi pada fotosintesis?', 'Fotosintesis berjalan lebih cepat', 'Fotosintesis tetap berjalan normal', 'Fotosintesis tidak bisa berjalan', 'Daun jadi tidak hijau', 'c', 'regular', 10, 15, 'Cahaya matahari adalah sumber energi utama fotosintesis. Tanpa cahaya, klorofil tidak dapat menangkap energi yang diperlukan untuk mengubah CO₂ dan air menjadi glukosa, sehingga fotosintesis tidak dapat berlangsung.', NOW(), NOW()),

(1, 'Jika tanah kering, mengapa fotosintesis terganggu?', 'Karena tidak ada oksigen', 'Karena akar tidak bisa menyerap air', 'Karena daun kehilangan warna hijau', 'Karena stomata tertutup', 'b', 'regular', 10, 15, 'Air adalah salah satu bahan baku utama fotosintesis. Jika tanah kering, akar tidak dapat menyerap air yang cukup, sehingga proses fotosintesis terganggu karena kekurangan bahan baku.', NOW(), NOW()),

(1, 'Berikut ini yang BUKAN bahan yang diperlukan untuk fotosintesis adalah…', 'Air (H₂O)', 'Karbon dioksida (CO₂)', 'Cahaya matahari', 'Protein', 'd', 'regular', 10, 15, 'Fotosintesis memerlukan tiga komponen utama: air (H₂O) dari akar, karbon dioksida (CO₂) dari udara, dan cahaya matahari sebagai sumber energi. Protein bukan bahan yang diperlukan dalam fotosintesis.', NOW(), NOW());

-- HOTS Questions (7 total - sistem akan random pilih sesuai kebutuhan)
INSERT INTO questions (module_id, question, option_a, option_b, option_c, option_d, correct_answer, question_type, read_time, answer_time, explanation, created_at, updated_at) VALUES
(1, 'Seorang siswa menaruh tanaman di ruang gelap selama seminggu. Daunnya berubah pucat dan tanaman layu. Apa penyebab utama kondisi tersebut?', 'Tanaman kekurangan air', 'Tidak ada cahaya matahari sebagai sumber energi fotosintesis', 'Tanaman tidak menyerap oksigen', 'Tanaman terlalu banyak karbondioksida', 'b', 'hots', 15, 20, 'Tanpa cahaya matahari, klorofil tidak dapat menangkap energi untuk proses fotosintesis. Akibatnya tumbuhan tidak dapat membuat glukosa sebagai makanan, sehingga daun menjadi pucat dan tanaman layu karena kekurangan energi.', NOW(), NOW()),

(1, 'Dua tanaman disiram dengan jumlah air yang sama. Tanaman A terkena sinar matahari langsung, Tanaman B berada di ruangan gelap. Setelah 5 hari, Tanaman A segar sementara Tanaman B layu. Mengapa Tanaman A lebih bertahan?', 'Tanaman A mendapat cahaya matahari untuk fotosintesis', 'Tanaman B tidak menyerap air dengan baik', 'Tanaman A tidak membutuhkan karbon dioksida', 'Tanaman B kelebihan oksigen', 'a', 'hots', 15, 20, 'Tanaman A mendapat cahaya matahari yang diperlukan untuk fotosintesis, sehingga dapat membuat makanan (glukosa) dan tetap hidup. Tanaman B tidak mendapat cahaya, tidak dapat berfotosintesis, dan akhirnya layu karena kehabisan energi.', NOW(), NOW()),

(1, 'Jika udara sekitar tercemar sehingga kadar karbon dioksida menurun, apa akibatnya bagi tumbuhan?', 'Fotosintesis tetap berjalan normal', 'Fotosintesis terganggu karena kekurangan bahan utama', 'Fotosintesis lebih cepat karena udara panas', 'Fotosintesis berhenti karena klorofil rusak', 'b', 'hots', 15, 20, 'CO₂ adalah salah satu bahan baku utama fotosintesis. Jika kadar CO₂ menurun, tumbuhan kekurangan bahan untuk membuat glukosa, sehingga proses fotosintesis menjadi terganggu dan tidak optimal.', NOW(), NOW()),

(1, 'Sebuah tanaman diletakkan di akuarium tertutup berisi air dan mendapat sinar matahari, tetapi udara luar tidak bisa masuk. Setelah beberapa hari tanaman tampak tidak sehat. Mengapa demikian?', 'Kekurangan air dari tanah', 'Kekurangan karbon dioksida dari udara luar', 'Kekurangan cahaya matahari', 'Kekurangan klorofil', 'b', 'hots', 15, 20, 'Meskipun ada air dan cahaya, tanaman membutuhkan CO₂ dari udara untuk fotosintesis. Karena akuarium tertutup, CO₂ tidak dapat masuk dari luar, sehingga tanaman kekurangan bahan baku untuk membuat makanan.', NOW(), NOW()),

(1, 'Dua tanaman tumbuh di kondisi berbeda. Tanaman 1 di tanah kering, Tanaman 2 di tanah lembab. Keduanya mendapat cahaya dan udara cukup. Mengapa Tanaman 1 tidak bisa melakukan fotosintesis dengan baik?', 'Karena tanah kering membuat akar tidak bisa menyerap air', 'Karena cahaya matahari terlalu sedikit', 'Karena klorofil di daun tidak aktif', 'Karena tanah lembab lebih banyak karbon dioksida', 'a', 'hots', 15, 20, 'Air adalah bahan baku penting untuk fotosintesis. Jika tanah kering, akar tidak dapat menyerap air yang cukup, sehingga proses fotosintesis terganggu karena kekurangan salah satu komponen utama.', NOW(), NOW()),

(1, 'Apa dampak terbesar bagi manusia dan hewan jika fotosintesis tidak pernah ada di bumi?', 'Tidak ada karbon dioksida di udara', 'Tidak ada makanan dan oksigen yang cukup', 'Tidak ada cahaya matahari', 'Tidak ada air di bumi', 'b', 'hots', 15, 20, 'Fotosintesis menghasilkan oksigen untuk bernapas dan glukosa sebagai dasar rantai makanan. Tanpa fotosintesis, tidak ada oksigen untuk bernapas dan tidak ada sumber makanan bagi semua makhluk hidup di bumi.', NOW(), NOW()),

(1, 'Mengapa daun disebut sebagai "dapur makanan" tumbuhan, bukan batang atau akar?', 'Karena daun berwarna hijau', 'Karena daun memiliki klorofil dan stomata untuk fotosintesis', 'Karena batang tidak menyerap air', 'Karena akar hanya menyalurkan karbon dioksida', 'b', 'hots', 15, 20, 'Daun disebut "dapur makanan" karena di daun terdapat klorofil untuk menangkap cahaya dan stomata untuk pertukaran gas, sehingga proses fotosintesis (membuat makanan) terjadi di daun.', NOW(), NOW());
