# version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    restart: on-failure
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /internal

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lidm
      MYSQL_USER: lidm
      MYSQL_PASSWORD: lidm
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge